# Generated by Django 3.0.10 on 2021-01-02 05:28

from django.db import migrations, models
import proApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='id',
            field=models.CharField(default=proApp.models.increment_role_id, max_length=25, primary_key=True, serialize=False),
        ),
    ]
